# Generated by Django 4.1 on 2022-09-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rand',
            name='category',
            field=models.CharField(choices=[('pork', 'pork'), ('chicken', 'chicken'), ('beef', 'beef'), ('fish', 'fish'), ('vegetarian', 'vegetarian')], max_length=100),
        ),
    ]
