# Generated by Django 4.1 on 2022-09-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rand', '0002_alter_rand_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rand',
            name='category',
            field=models.CharField(choices=[('pork', 'pork'), ('chicken', 'chicken'), ('vegetarian', 'vegetarian')], max_length=100),
        ),
    ]
