# Generated by Django 4.1 on 2022-09-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rand', '0003_alter_rand_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rand',
            name='cuisine',
            field=models.CharField(choices=[('american', 'american'), ('australian', 'australian'), ('european', 'european')], max_length=100),
        ),
    ]
